### ISSUE TITLE
[RFC] Remove extra echo before command execution

### ISSUE THREAD

**Issue by SebLours** [caillioux/dockerexec#1]
Hi,

When i use dockerexec for example as this
`(dockerexec app:database:generate-sql-reset db_test tests/config/mysql/dump.cnf ) > db_test.sql` to generate a sql output, the command output is prefixed by the info message 
`xxx_php:/apps/symfony #  "bin/console" "app:database:generate-sql-reset" "db_test" "tests/config/mysql/dump.cnf"` and my sql output is contaminated by the info message.

What do you think about removing the extra echo before the command execution?
`echo "$container:$workdir # $user_command"`

**Comment by Florent-Emagma** [comment]
Hope it will be fixed soon too !

**Comment by caillioux** [comment]
Well @SebLours, I think this is manageable and as you know, me and I at caillioux pay a lot of attention to process quickly our customer requests, I escalate the demand to our tech collegues for an update.

**Comment by caillioux** [comment]
Ok, it's been a bit long, but you know have an optional option `-v` to display the echo.
Sorry for the BC break, had no choice 🤷

**Comment by SebLours** [comment]
Thanks a lot! What a velocity!
